### ISSUE TITLE
能问下，为什么每次运行程序时，都只能下载两张图片（免费的漫画也是），然后说要先购买（我明明在火狐登录了账号，并且也购买了），谢谢了

### ISSUE THREAD

**Issue by niuqudechongdong** [LaMP57/BilibiliMangaDownload#1]

**Comment by LaMP57** [comment]
麻烦提供一下有问题的漫画mc号。
我刚测试了一下，下载免费漫画并没有发现这个问题。
其实现在的下载方式非常不优雅，本月应该会更新一次，会大幅提升稳定性和下载速度。

**Comment by LaMP57** [comment]
新版本已经更新，不再需要安装火狐浏览器，稳定性和下载速度都得到了极大提升，欢迎试用。

**Comment by niuqudechongdong** [comment]
不好意思，现在才看到，我之前试了好几个漫画，包括海贼王那些（5月之前是全免费的），都不行，我现在试一下新的版本。作者辛苦了。

**Comment by niuqudechongdong** [comment]
现在可以了，谢谢大佬，感觉你这个程序好厉害，一百行的代码都不用，就能实现下载，再次感谢大佬。顺便问一下大佬，大佬还有其他关于bilibili漫画的黑科技吗？比如自动签到

**Comment by niuqudechongdong** [comment]
现在可以了，谢谢大佬，感觉你这个程序好厉害，一百行的代码都不用，就可以实现下载，再次感谢大佬。顺便问一下大佬，大佬还有其他关于bilibili漫画的黑科技吗？比如自动签到

**Comment by LaMP57** [comment]
并不是大佬😂这次新版本的核心部分是参考了别人的代码。
自动签到看了一下似乎只能在APP中操作，有空我试一下吧。

**Comment by niuqudechongdong** [comment]
还是要感谢作者你的。
我也没有在网页端看到有签到的按钮
