### ISSUE TITLE
B漫→月光下的异世界之旅 无法下载

### ISSUE THREAD

**Issue by xuelandongman** [LaMP57/BilibiliMangaDownload#10]
B漫→月光下的异世界之旅 下载失败，提示：FileNotFoundError: [WinError 3] 系统找不到指定的路径。
https://manga.bilibili.com/detail/mc30152

但是其他漫画下载时，却没有这样的问题。

有时候下载其他漫画的时候，还会显示：
[ERROR]downloads/开挂药师的异世界悠闲生活/3 有隐情的房子/16.jpg 下载失败，重试中...
[ERROR]downloads/开挂药师的异世界悠闲生活/3 有隐情的房子/28.jpg 下载失败，重试中...
不知道问题大不大？

**Comment by LaMP57** [comment]
请尝试更新到最新版本，刚才合并的pr应该已经修复了这个问题

**Comment by LaMP57** [comment]
抱歉，经测试该问题仍然存在。稍等，很快将会修复

**Comment by xuelandongman** [comment]
谢谢 刚刚试了一下 问题解决啦 东西很好用的！

**Comment by xuelandongman** [comment]
[ERROR]D:\IDM\BilibiliMangaDownload/【轻小说】如果究极进化的完全沉浸式RPG比现实更垃圾的话/第7章 垃圾游戏的极致/49.jpg图 片下载失败

https://manga.bilibili.com/mc29694/635028?from=manga_detail

**Comment by LaMP57** [comment]
已优化处理方式，请更新后再试。
