### ISSUE TITLE
[ERROR]D:\IDM\BilibiliMangaDownload/【轻小说】如果究极进化的完全沉浸式RPG比现实更垃圾的话/第7章 垃圾游戏的极致/49.jpg图 片下载失败

### ISSUE THREAD

**Issue by xuelandongman** [LaMP57/BilibiliMangaDownload#11]
[ERROR]D:\IDM\BilibiliMangaDownload/【轻小说】如果究极进化的完全沉浸式RPG比现实更垃圾的话/第7章 垃圾游戏的极致/49.jpg图 片下载失败

https://manga.bilibili.com/mc29694/635028?from=manga_detail

**Comment by LaMP57** [comment]
已优化处理方式，请更新后再试。
