### ISSUE TITLE
可以更改输入章节号为输入第几话，然后就可以改变章节名的获取方式

### ISSUE THREAD

**Issue by lhz07** [LaMP57/BilibiliMangaDownload#14]
这样更符合使用习惯，也不会那么麻烦
具体的实现方式：
    ComicDetail 中的 ep_list 是一个列表中嵌套字典，而这个列表的排列方式是从第0项到（所有章节数-1）项，按着从新到旧的顺序排，也就是说第0项是最新一话。
    所以，用列表长度减去输入的第几话，得到的数字就是相对应的列表项。直接选取对应的列表项，就可以获取那一章节的所有信息，而不用遍历整个列表去寻找章节名。

**Comment by LaMP57** [comment]
这个方案我也考虑过，但实际中发现部分漫画章节号并非连续。
可能会存在类似 “第1章、番外1、第2章” 或 “第一章(上)、第一章(下)” 这样的特殊情况，使用户不易计算需要输入的数字。
所以最终没有采取这种方案。
