### ISSUE TITLE
chName末尾可能存在空格，导致windows下下载文件失败

### ISSUE THREAD

**Issue by zhongfly** [LaMP57/BilibiliMangaDownload#2]
代码中chName(章节名)是由short_title和title拼接而成的，前者必存在不为空，但后者可能出现为空，其值为“ "一个空格。而在windows平台下，文件夹末尾是不允许有空格的(但是可以新建末尾有空格的文件夹)，导致无法在这样末尾有空格的文件夹内新建xx.jpg文件，最终报错。
示例：mc27866的隐瞒之事 下载会导致报错
另外，有些漫画的漫画名带有特殊符号，例如mc25480和mc26941，同样会导致异常文件夹

**Comment by LaMP57** [comment]
感谢反馈。问题已修复。
