### ISSUE TITLE
出现异常 not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by nebulas-star** [LaMP57/BilibiliMangaDownload#3]
![image](https://user-images.githubusercontent.com/33574791/97131538-648a4200-177f-11eb-9812-79fff20aee3c.png)
python版本3.7
IDE为VS2019
请问Cookie字符串是需要满足什么要求吗？

**Comment by LaMP57** [comment]
这里的cookie的是：
`LIVE_BUVID=xxx; stardustvideo=1; buvid3=xxx; fts=xxx; rpdid=xxx; CURRENT_QUALITY=80; ..........`
这样的格式
我看了一下chorme和firefox都是这样的显示格式，你是复制的什么浏览器的cookie？

**Comment by nebulas-star** [comment]
![Snipaste_10 26 12 03 41 521](https://user-images.githubusercontent.com/33574791/97133017-930a1c00-1783-11eb-871c-8bef195aa4ec.png)
chrome的。

> 这里的cookie的是：
> `LIVE_BUVID=xxx; stardustvideo=1; buvid3=xxx; fts=xxx; rpdid=xxx; CURRENT_QUALITY=80; ..........`
> 这样的格式
> 我看了一下chorme和firefox都是这样的显示格式，你是复制的什么浏览器的cookie？

**Comment by LaMP57** [comment]
更新一下试试
现在只需要输入cookie里的SESSDATA的值就可以了
应该不会报错了

**Comment by nebulas-star** [comment]
好了
![image](https://user-images.githubusercontent.com/33574791/97134918-bfc13200-1789-11eb-83e3-a701b5adba12.png)
顺带报一下中间有没买的话数就会卡在这一话（诶为啥我没买全？） 

> 更新一下试试
> 现在只需要输入cookie里的SESSDATA的值就可以了
> 应该不会报错了

**Comment by LaMP57** [comment]
好的 这个问题也解决了

**Comment by nebulas-star** [comment]
> 好的这个问题也解决了

![image](https://user-images.githubusercontent.com/33574791/97139228-0700f000-1795-11eb-8f1d-dd6edd2e0f98.png)
依旧..爆了诶...

**Comment by LaMP57** [comment]
是的 本地处理好了没上传😂
现在好了

**Comment by nebulas-star** [comment]
> 是的本地处理好了没上传😂
> 现在好了

OK这回没问题了
