### ISSUE TITLE
部分图片不完整，图片大面积灰色

### ISSUE THREAD

**Issue by dbcooper7z** [LaMP57/BilibiliMangaDownload#6]
部分图片不完整，图片大面积灰色，希望可以加入校验图片完整性的代码。

**Comment by prnake** [comment]
提供一种可行的思路
```python
def isValidImage(path):
    with open(path, "rb") as f:
        if path.endswith('.jpg'):
            valid = f.read().endswith(b'\xff\xd9')
        elif path.endswith('.png'):
            valid = f.read().endswith(b'\xaeB`\x82')
        else:
            valid = True
    try:
        Image.open(path).verify()
    except:
        valid = False
    return valid
def downloadImage(url, path):
    if not os.path.exists(path):
        r = requests.get(url, stream = True, cookies = cookies)
        f = open(path, 'wb')
        for chunk in r.iter_content(chunk_size = 1024):
            if chunk:
                f.write(chunk)
        f.close()
    if not isValidImage(path):
        print(path + " download failed, retrying...")
        os.remove(path)
        downloadImage(url, path)
```

**Comment by LaMP57** [comment]
> 提供一种可行的思路
> 
> ```python
> def isValidImage(path):
>     with open(path, "rb") as f:
>         if path.endswith('.jpg'):
>             valid = f.read().endswith(b'\xff\xd9')
>         elif path.endswith('.png'):
>             valid = f.read().endswith(b'\xaeB`\x82')
>         else:
>             valid = True
>     try:
>         Image.open(path).verify()
>     except:
>         valid = False
>     return valid
> def downloadImage(url, path):
>     if not os.path.exists(path):
>         r = requests.get(url, stream = True, cookies = cookies)
>         f = open(path, 'wb')
>         for chunk in r.iter_content(chunk_size = 1024):
>             if chunk:
>                 f.write(chunk)
>         f.close()
>     if not isValidImage(path):
>         print(path + " download failed, retrying...")
>         os.remove(path)
>         downloadImage(url, path)
> ```

感谢，将于下周加入相关功能，也欢迎直接提pr~
